name: Build

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v4.4
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo $IDF_PATH
        echo $(ls)
        . $IDF_PATH/export.sh
        idf.py build
    - name: Upload ERC Error Report
      uses: actions/upload-artifact@v3
      with:
        name: build_artifacts
        path: reflow_oven_controller/build
  
